deployment:
  replicaCount: 3
  ingress:
    hosts:
      - host: kalupo-ecommerce.codev-prod.com
        paths:
          - /

  extraEnvs: 
    # - name: AWS_BUCKET_NAME
    #   value: cdv-prod-clubpyme-224434642118-us-east-1
    # - name: AWS_BUCKET_REGION
    #   value: us-east-1
    # - name: AWS_BUCKET_URL
    #   value: content-kalupo-ecommerce.codev-prod.com
    - name: NODE_ENV
      value: production

  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 25
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 90

  podDistuptionBudget:
    enabled: true
    # Solo puede estar activo 1 al tiempo
    # maxUnavailable: 1
    minAvailable: 2


